webtemp/bloggy/urls.py
from django.urls import path
from . import views

app_name = "bloggy"
urlpatterns = [
    path("", views.index, name="index"),
    path("explore/", views.explore, name="explore"),
    path("article/<str:slug>", views.article, name="article"),
    path("search", views.search, name="search"),
    path("q", views.q, name="query"),
    path("t", views.t, name="trending")
]

webtemp/webtemp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('bloggy.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webtemp/bloggy/models.py
from django.db import models

from re import sub
from random import randint
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return f"{self.name}"

class Article(models.Model):
    title = models.CharField(verbose_name="Name of Article", max_length=50, name="title", unique=True)
    created = models.DateTimeField(auto_now_add=True)
    cover = models.ImageField(verbose_name="Cover image", upload_to='images/%Y/%m/%d/', blank=True)
    tags = models.ManyToManyField(Tag, verbose_name="Tags", blank=True)
    body = models.TextField(verbose_name="Article content", name="content")
    escaped_body = models.TextField(blank=True, editable=False)
    stem_body = models.TextField(blank=True, editable=False)
    views = models.BigIntegerField(default=0)
    slug = models.SlugField(unique=True, blank=True)
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = sub("[^\s\w]", "", self.title.lower()).replace(" ", "-") + str(randint(100000, 999999))
            while Article.objects.filter(slug=slug):
                slug = slug[:-6] + str(randint(100000, 999999))
            self.slug = slug
        self.escaped_body = sub('<[^<]+?>', '', self.content)
        ps = PorterStemmer()
        for i in word_tokenize(self.escaped_body):
            self.stem_body += ps.stem(i) + " "
        super(Article, self).save(*args, **kwargs)
    def __str__ (self):
        return f"{self.title}"

webtemp/bloggy/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.conf import settings
from django.db.models import Count

from itertools import chain
from re import sub
from collections import Counter
import datetime
from nltk.stem import PorterStemmer

from .models import Article

# Create your views here.

def query(q, model):
    exact = model.objects.filter(title__iexact=q)
    contains = model.objects.filter(title__contains=q)
    return list(chain(exact, contains))

def index(request):
    return render(request, "bloggy/index.html")

def explore(request):
    return render(request, "bloggy/explore.html")

def article(request, slug):
    article = Article.objects.get(slug=slug)
    article.views += 1
    article.save()
    print(article.stem_body)
    related = Article.objects.exclude(id=article.id).filter(tags__in=article.tags.all()).annotate(
        matches=Count('tags')
    ).order_by('-matches')
    if len(related) > 3:
        related = related[:3]
    return render(request, "bloggy/article.html", {
        "article": article,
        "MEDIA_URL": settings.MEDIA_URL,
        "related": related,
    })

# search results
def search(request):
    try:
        q = request.GET["q"]
        q = sub(' +', ' ', sub("\W", " ", q)).strip()
        query = q.split(" ")
        results = []
        ps = PorterStemmer()
        # sort articles by relevance: # distinct words from query in article
        for word in query:
            stem_word = ps.stem(word)
            q_result = []
            q_result.extend(Article.objects.filter(title__icontains=word))
            q_result.extend(Article.objects.filter(stem_body__icontains=stem_word))
            print(ps.stem(word))
            q_result.extend(Article.objects.filter(tags__name__icontains=word))
            results.extend([i for i, j in Counter(q_result).most_common()])
        results = [i for i, j in Counter(results).most_common()]
    except:
        q = None
        results = []
    return render(request, "bloggy/search.html", {
        "results": results,
        "q": q
    })

# input results (by title)
def q(request):
    # TODO: ADD validation
    if request.method == 'GET':
        # query database
        q_results = query(request.GET["q"], Article)
        results = {}
        # for each query results append to json list
        for article in q_results:
            di = {}
            di["title"] = article.title
            di["slug"] = article.slug
            results[article.id] = di
        return JsonResponse(results)

# top article
def t(request):
    # TODO: ADD validation
    if request.method == 'GET':
        # query database
        trending = Article.objects.filter(created__gte=datetime.date.today() - datetime.timedelta(days=7)).order_by("-views")[:5]
        results = {}
        # for each query results append to json list
        for article in trending:
            di = {}
            di["views"] = article.views
            di["slug"] = article.slug
            results[article.title] = di
        return JsonResponse(results)

webtemp/bloggy/templates/bloggy/article.html
{% extends 'layouts/layout.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/article.css' %}">
{% endblock %}
{% block body %}
<div id="content">
    <div class="article">
        <h2 class="ac-title">{{ article.title }}</h2>
        <p class="ac-author italic">Posted {{ article.created | date:"M d, Y" }} | By Anon Y. Mousse</p>
        {% if article.cover %}
            <div class="ac-ci-ctr1">
                <div id="ac-ci-ctr2">
                    <img src="{{ MEDIA_URL }}{{ article.cover }}" alt="Hummingbird" class="ac-ci">
                    <p class="caption">
                        The Critically Endangered Loremipsum Hummingbird from Western Cuba is here caught on camera by Anon Y. Mousse. This species is extremely elusive, so exact counts of the population remain uncertain. 
                    </p>
                    <p class="caption">
                        &copy; 2022 The Website / Anon Y. Mousse
                    </p>
                </div>
            </div>
        {% endif %}
        {% autoescape off %}
            {{ article.content }}
        {% endautoescape %}
    </div>
    <div class="readbar">
        {% if related %}
        <h2>Related Posts</h2>
        <ul class="no-format-ul readbar-ul">
            {% for link in related %}
            <a href="{% url 'bloggy:article' link.slug %}" class="no-format-a">
                <li class="ac-thbn">
                    <div class="ac-thbn-img-ctr">
                        {% if link.cover %}
                            <img src="{{ MEDIA_URL }}{{ link.cover }}" alt="Finch" class="ac-thbn-img">
                        {% else %}
                            <img src="https://images.unsplash.com/photo-1668069676044-3aa1cda3c067?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=300&utm_source=unsplash_source&w=300" alt="Dragonfly" class="ac-thbn-img">
                        {% endif %}
                    </div>
                    <div class="ac-thbn-heading">
                        <h4>{{ link.title }}</h4>
                    </div>
                    <div class="ac-tbhn-read">
                        <button class="ac-thbn-read-btn">Read More</button>
                    </div>
                </li>
            </a>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

webtemp/bloggy/templates/bloggy/explore.html
{% extends 'layouts/layout.html' %}
{% block title %}Explore The World{% endblock %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/explore.css' %}">
{% endblock %}
{% block body %}
    <div id="banner-explore" class="banner">
        <div class="cutout">
            <h1>EXPLORE</h1>
        </div>
    </div>
    <div id="banner-galleries" class="banner layer-2">
        <div class="hover-fade-banner">
            <div class="block-left block-an"></div>
            <div id="band-gal" class="band-mid-blk band-left">
                <h1>GALLERIES</h1>
                <p class="center-txt">Gorgeous Testimonies of God's Majesty</p>
            </div>
        </div>
    </div>
    <a href="article.html" class="no-format-a">
        <div id="banner-articles" class="banner layer-2">
            <div class="hover-fade-banner">
                <div class="block-right block-an"></div>
                <div id="band-ac" class="band-mid-blk band-right">
                        <h1>ARTICLES</h1>
                        <p class="center-txt">Be Encouraged. Be Convicted.</p>
                </div>
            </div>
        </div>
    </a>
    <div class="band-left"></div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/explore.js' %}"></script>
{% endblock %}

webtemp/bloggy/templates/bloggy/index.html
{% extends 'layouts/layout.html' %}
{% block title %}Welcome to The World{% endblock %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/article.css' %}">
{% endblock %}
{% block body %}

<div id="content">
    <div class="readbar">
        <h2>Popular Articles</h2>
        <div id="featured-ac">
            <img src="https://images.unsplash.com/photo-1648425024972-64303b9d353f?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&w=800" alt="Lake Tahoe" id="featured-ac-img">
            <h3 class="layer-2">Water and Life: Proof of a Creator</h3>
            <div id="line-ctr" class="layer-2"></div>
            <div class="gradient-top"></div>
        </div>
        <ul class="no-format-ul readbar-ul">
            <li class="ac-thbn">
                <div class="ac-thbn-img-ctr">
                    <img src="https://images.unsplash.com/photo-1608235472173-d4918c4aeb49?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=300&w=300" alt="Banff" class="ac-thbn-img">
                </div>
                <div class="ac-thbn-heading">
                    <h4>Mountains From the Flood</h4>
                </div>
                <div class="ac-tbhn-read">
                    <button class="ac-thbn-read-btn">Read More</button>
                </div>
            </li>
            <li class="ac-thbn">
                <div class="ac-thbn-img-ctr">
                    <img src="https://images.unsplash.com/photo-1503343870946-44cccad5de1b?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=300&w=300" alt="Sun" class="ac-thbn-img">
                </div>
                <div class="ac-thbn-heading">
                    <h4>The Earth's Solar Protection</h4>
                </div>
                <div class="ac-tbhn-read">
                    <button class="ac-thbn-read-btn">Read More</button>
                </div>
            </li>
            <li id="ac-thbn3" class="ac-thbn">
                <div class="ac-thbn-img-ctr">
                    <img src="https://images.unsplash.com/photo-1564198729838-cb82ee0c733c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=300&w=300" alt="Baobab tree" class="ac-thbn-img">
                </div>
                <div class="ac-thbn-heading">
                    <h4>Photos of Madagascar</h4>
                </div>
                <div class="ac-tbhn-read">
                    <button class="ac-thbn-read-btn">Read More</button>
                </div>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

webtemp/bloggy/templates/bloggy/search.html
{% extends 'layouts/layout.html' %}
{% block title %}Search Results{% endblock %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock %}
{% block body %}
<div id="content">
    <div id="vis-searchbar-ctr">
        <form action="{% url 'bloggy:search' %}" id="vis-searchform">
            <input type="text" name="q" id="vis-searchbar" placeholder="Search the world of animals..." autocomplete="off" {% if q %}value="{{ q }}"{% endif %}>
            <button type="submit" id="vis-search-submit">
                <i class="material-icons" style="font-size:28px">&#xe8b6;</i>
            </button>
            <ul id="vis-search-ac-menu">
            </ul>
        </form>
    </div>
    <h1 class="m-20">Search Results{% if q %} for <em>{{ q }}</em>{% endif %}</h1>
    {% if results %}
    <ul class="no-format-ul">
            {% for result in results %}
                <li class="q-result-li">
                    <a href="{% url 'bloggy:article' result.slug %}" class="q-result-a">
                        <h3>{{ result.title }}</h3>
                        <p>{{ result.escaped_body | truncatechars:440 }}</p>
                    </a>
                </li>
            {% endfor %}
    </ul>
    {% else %}
    No results
    {% endif %}
</div>
{% endblock %}
{% block script %}
<script src="{% static 'js/search.js' %}"></script>
{% endblock %}

webtemp/bloggy/templates/layouts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/body.css' %}">
    {% block head %}{% endblock %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <nav id="nav">
        <div id="heading" class="nav-btn">
            <a href="/" class="no-format-a">
                <h2> The Website </h2>
            </a>
        </div>
        <ul id="navbar" class="no-format-ul">
            <li>
                <a href="{% url 'bloggy:explore' %}" id="explore-btn" class="nav-btn">
                    Explore
                </a>
            </li>
            <li>
                <a href="#" id="about-btn" class="nav-btn">
                    Donate
                </a>
            </li>
            <li>
                <a href="#" id="store-btn" class="nav-btn">
                    Store
                    <div id="swoosh-ctr">
                        <div id="swoosh"></div>
                    </div>
                </a>
            </li>
        </ul>
        <div id="search">
            <ul id="icobar" class="no-format-ul">
                <li id="search-ico-ctr">
                    <a href="#" id="search-ico" class="nav-btn">
                        <i class="material-icons" style="font-size:28px">&#xe8b6;</i>
                    </a>
                </li>
                <li id="menu-ico-ctr">
                    <a href="#" id="menu-ico" class="nav-btn">
                        <i class="material-icons" style="font-size:28px">&#xe5d2;</i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div id="searchbar-ctr" class="layer-10">
        <form action="{% url 'bloggy:search' %}" id="searchform" method="get">
            <input type="text" name="q" id="searchbar" placeholder="Search the world of animals..." autocomplete="off">
            <button type="submit" id="search-submit">
                <i class="material-icons" style="font-size:28px">&#xe8b6;</i>
            </button>
            <ul id="search-ac-menu">
            </ul>
        </form>
    </div>
    <div id="nav-menu">
        <div id="nav-menu-content">
            <h2>The Website</h2>
            <ul id="nav-menu-bar" class="no-format-ul">
                <a href="{% url 'bloggy:explore' %}" class="menu-btn"><li>Explore</li></a>
                <a href="#" class="menu-btn"><li>About</li></a>
                <a href="#" class="menu-btn"><li>Subscribe</li></a>
                <a href="#" class="menu-btn"><li>Donate</li></a>
                <a href="#" class="menu-btn"><li>Store</li></a>
            </ul>
            <div id="close-menu-ctr">
                <div id="close-menu">&times;</div>
            </div>
        </div>
    </div>
    <main>
        {% block body %}{% endblock %}
    </main>
    <footer>
        <div id="column1" class="ft-column">
            <div class="ft-top-row">
                <div id="ft-about">
                    <h1>The Website</h1>
                    <p>
                        The Website is a 503(c) non-profit organization, dedicated to educating the public about the beauty of animal life. All donations are tax-deductable.
                    </p>
                </div>
                <div id="ft-list-ctr">
                    <div>
                        <ul class="no-format-ul ft-list">
                            <li><a href="{% url 'bloggy:explore' %}">Explore</a></li>
                            <li><a href="#">Donate</a></li>
                            <li><a href="#">Store</a></li>
                        </ul>
                    </div>
                    <div>
                        <ul class="no-format-ul ft-list">
                            <li><a href="#">About</a></li>
                            <li><a href="#">Subscribe</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div>
                <p class="copyright">&copy; 2022 | The Website | Anon Y. Mousse</p>
            </div>
        </div>
    </footer>
    <script> </script>
    <script src="{% static 'js/window_size.js' %}"></script>
    <script src="{% static 'js/align.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script>
    {% block script %}{% endblock %}
</body>
</html>